version: "3"

volumes:
  database:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  app-backend:
    build: ./backend
    working_dir: /app
    depends_on:
      - database
    volumes:
      - ./backend:/app

  app-frontend:
    build: ./frontend
    working_dir: /app
    depends_on:
      - app-backend
    volumes:
      - ./frontend:/app

  database:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=birdboard
      - MYSQL_ROOT_PASSWORD=password
